/// @description Insert description here
velocity = 0;
magnitude = random_range(-.02, -.01);

init = false;
top_x = xstart;
top_y = ystart - 100;

// This code is generated by KeeVee Games Fixture Editor.
// Place this code in the Create event or similar.

var fix, offsetx, offsety;

offsetx = sprite_width/2-sprite_xoffset;
offsety = sprite_height/2-sprite_yoffset;


fix[0] = physics_fixture_create();
physics_fixture_set_circle_shape(fix[0], 24);

fix[1] = physics_fixture_create();
physics_fixture_set_polygon_shape(fix[1]);
physics_fixture_add_point(fix[1], 6, -9);
physics_fixture_add_point(fix[1], 6, 103);
physics_fixture_add_point(fix[1], -4, 103);
physics_fixture_add_point(fix[1], -4, -9);

fix[2] = physics_fixture_create();
physics_fixture_set_circle_shape(fix[2], 24);

for (var i = 0; i < 3; i += 1) {
  physics_fixture_set_density(fix[i], 0.00);
  physics_fixture_set_friction(fix[i], 0.20);
  physics_fixture_set_linear_damping(fix[i], 0.10);
  physics_fixture_set_angular_damping(fix[i], 0.10);
  physics_fixture_set_restitution(fix[i], 0.10);
  physics_fixture_set_sensor(fix[i], 0);
  physics_fixture_set_awake(fix[i], 1);
  physics_fixture_bind_ext(fix[i], id, 2-offsetx, 72-offsety);
  physics_fixture_delete(fix[i]);
}